import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.array([10,20,30,40,50])
print(arr)
print(arr+1)
print(arr*2)
print(arr-2)
print(np.sum(arr))
print(np.subtract(arr,2))
print(np.mean(arr))
print(arr)
print(np.max(arr))
print(arr+arr1)